#!/bin/sh
app=/home/boyuu/tools/commu4scnet
mac3h=b0-e0-14
if [ $# -lt 1 ]; then
  echo "Usage: scnettool mac_address"
  echo "       scnettool [option] mac_address"
  echo "          option: get set"
  exit 0
fi

if [ $# -eq 1 ]; then
  echo $app -m ${mac3h}-$1
else
  if [ $1 = "get" ]; then
    $app -g $2.cfg ${mac3h}-$2 
    tftp -p -l $2.cfg 192.168.1.3
  elif [ $1 = "set" ]; then
    tftp -g -r $2.cfg 192.168.1.3
    $app -s $2.cfg ${mac3h}-$2
  fi
fi

